-- MySQL Script generated by MySQL Workbench
-- Mon Apr 10 01:48:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`y_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`y_user` (
  `y_user_id` INT NOT NULL AUTO_INCREMENT,
  `google_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`y_user_id`),
  UNIQUE INDEX `google_id_UNIQUE` (`google_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media` (
  `media_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `viwes` INT NULL DEFAULT NULL,
  `age_restriction_id` INT NOT NULL,
  `autor_id` INT NOT NULL,
  `monetization` INT NOT NULL,
  `mediacol` VARCHAR(200) NULL DEFAULT NULL,
  `y_user_y_user_id` INT NOT NULL,
  PRIMARY KEY (`media_id`),
  UNIQUE INDEX `media_id_UNIQUE` (`media_id` ASC) VISIBLE,
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC) VISIBLE,
  UNIQUE INDEX `age_restriction_id_UNIQUE` (`age_restriction_id` ASC) VISIBLE,
  UNIQUE INDEX `autor_id_UNIQUE` (`autor_id` ASC) VISIBLE,
  INDEX `fk_media_y_user1_idx` (`y_user_y_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_media_y_user1`
    FOREIGN KEY (`y_user_y_user_id`)
    REFERENCES `mydb`.`y_user` (`y_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`age_restriction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`age_restriction` (
  `id_age_restriction` INT NOT NULL AUTO_INCREMENT,
  `age` INT NOT NULL,
  `media_media_id` INT NOT NULL,
  PRIMARY KEY (`id_age_restriction`),
  UNIQUE INDEX `id_age_restriction_UNIQUE` (`id_age_restriction` ASC) VISIBLE,
  UNIQUE INDEX `age_UNIQUE` (`age` ASC) VISIBLE,
  INDEX `fk_age_restriction_media1_idx` (`media_media_id` ASC) VISIBLE,
  CONSTRAINT `fk_age_restriction_media1`
    FOREIGN KEY (`media_media_id`)
    REFERENCES `mydb`.`media` (`media_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `media_media_id` INT NOT NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `id_category_UNIQUE` (`id_category` ASC) VISIBLE,
  UNIQUE INDEX `type_UNIQUE` (`type` ASC) VISIBLE,
  INDEX `fk_category_media1_idx` (`media_media_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_media1`
    FOREIGN KEY (`media_media_id`)
    REFERENCES `mydb`.`media` (`media_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `admin` VARCHAR(45) NOT NULL,
  `subscribers` INT NULL DEFAULT NULL,
  PRIMARY KEY (`group_id`),
  UNIQUE INDEX `group_id_UNIQUE` (`group_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profile` (
  `profile_id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `google_url` VARCHAR(100) NOT NULL,
  `subscribe` INT NULL DEFAULT NULL,
  `y_user_y_user_id` INT NOT NULL,
  PRIMARY KEY (`profile_id`),
  UNIQUE INDEX `profile_id_UNIQUE` (`profile_id` ASC) VISIBLE,
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC) VISIBLE,
  UNIQUE INDEX `google_url_UNIQUE` (`google_url` ASC) VISIBLE,
  INDEX `fk_profile_y_user_idx` (`y_user_y_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_profile_y_user`
    FOREIGN KEY (`y_user_y_user_id`)
    REFERENCES `mydb`.`y_user` (`y_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`y_user_has_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`y_user_has_group` (
  `y_user_y_user_id` INT NOT NULL,
  `group_group_id` INT NOT NULL,
  PRIMARY KEY (`y_user_y_user_id`, `group_group_id`),
  INDEX `fk_y_user_has_group_group1_idx` (`group_group_id` ASC) VISIBLE,
  INDEX `fk_y_user_has_group_y_user1_idx` (`y_user_y_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_y_user_has_group_group1`
    FOREIGN KEY (`group_group_id`)
    REFERENCES `mydb`.`group` (`group_id`),
  CONSTRAINT `fk_y_user_has_group_y_user1`
    FOREIGN KEY (`y_user_y_user_id`)
    REFERENCES `mydb`.`y_user` (`y_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
